services:
  web:
    build: .
    image: "${{secrets.DOCKER_USERNAME}}/pyserver:latest"
    ports:
      - "5000"
    environment:
        DB_HOST: db
        DB_NAME: pyserver
        DB_USER: postgres
        DB_PASSWORD: example
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: pyserver
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    networks:
      - app-network
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf


networks:
  app-network:
    driver: bridge

volumes:
  pg_data: