name: Build and push docker image

on:
  push:
    tags:
      - '*'
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Image Tag
        id: set-tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF/refs\/tags\//}"
          else
            TAG="latest"
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build Docker Image and List Docker Images
        run: |
          docker compose build
          echo $TAG
          docker image ls
          docker tag pyserver:latest ${{ secrets.DOCKER_USERNAME }}/pyserver:$TAG
          docker image ls

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/pyserver:$TAG